name: aiuta_flutter
description: "Aiuta Virtual Try-On Solution for Apparel and Fashion Businesses."
repository: "https://github.com/aiuta-com/flutter-sdk"
issue_tracker: "https://github.com/aiuta-com/flutter-sdk/issues"
homepage: "https://aiuta.com/"
version: 0.0.3

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <6.0.0"
  build_runner: ^2.4.9
  json_serializable: ^6.8.0


flutter:
  plugin:
    platforms:
      android:
        package: com.aiuta.flutter.fashionsdk
        pluginClass: AiutaPlugin
      ios:
        pluginClass: AiutaPlugin
