name: aiuta_flutter
description: "Aiuta Flutter SDK project."
version: 0.0.1
homepage: "https://aiuta.com/"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: "3.22.3"

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1


flutter:
  plugin:
    platforms:
      android:
        package: com.aiuta.flutter.fashionsdk
        pluginClass: AiutaPlugin
      ios:
        pluginClass: AiutaPlugin
