import 'package:aiuta_flutter/configuration/features/image_picker/predefined_model/aiuta_image_picker_predefined_model_data.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:aiuta_flutter/configuration/features/image_picker/predefined_model/aiuta_image_picker_predefined_model_icons.dart';
import 'package:aiuta_flutter/configuration/features/image_picker/predefined_model/aiuta_image_picker_predefined_model_strings.dart';

part 'aiuta_image_picker_predefined_model_feature.g.dart';

/// Configuration for the predefined model feature to use photos of
/// models with the different body types generated by Aiuta instead of
/// real users' photos.
@JsonSerializable()
class AiutaImagePickerPredefinedModelFeature {
  final AiutaImagePickerPredefinedModelData? data;

  /// Icons used in the predefined model feature.
  final AiutaImagePickerPredefinedModelIcons icons;

  /// Strings used in the predefined model feature.
  final AiutaImagePickerPredefinedModelStrings strings;

  /// Creates an [AiutaImagePickerPredefinedModelFeature] with the [icons] and
  /// [strings] configuration.
  AiutaImagePickerPredefinedModelFeature({
    this.data,
    required this.icons,
    required this.strings,
  });

  /// Creates a built-in predefined model feature configuration with default settings.
  factory AiutaImagePickerPredefinedModelFeature.builtIn() {
    return AiutaImagePickerPredefinedModelFeature(
      icons: AiutaImagePickerPredefinedModelIconsBuiltIn(),
      strings: AiutaImagePickerPredefinedModelStringsBuiltIn(),
    );
  }

  // Internal json staff
  factory AiutaImagePickerPredefinedModelFeature.fromJson(
          Map<String, dynamic> json) =>
      _$AiutaImagePickerPredefinedModelFeatureFromJson(json);

  Map<String, dynamic> toJson() =>
      _$AiutaImagePickerPredefinedModelFeatureToJson(this);
}
