name: Build release apk

on:
  workflow_dispatch:

concurrency:
  group: build-android-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_apk:
    name: Build release APK
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Base setup android
        uses: ./.github/actions/setup-android

      - name: Base setup flutter
        uses: ./.github/actions/setup-flutter

      - name: Build release apk
        run: |
          # Move to example project
          cd example
          # Start test apk
          flutter build apk --release

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: '**/build/app/outputs/apk/**/*.apk'
