name: Release on Pub Dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: release-pub-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_pub_dev:
    name: Release on pub dev
    runs-on: ubuntu-latest

    timeout-minutes: 180

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.USED_LFS }}
          fetch-depth: 0

      - name: Switch to master branch
        run: |
          git fetch origin main
          git checkout main

      - name: Base setup dart
        uses: dart-lang/setup-dart@v1

      - name: Base setup flutter
        uses: ./.github/actions/setup-flutter

      - name: Finalize_version
        run: bash scripts/finalize_changelog_versions.sh

      - name: Set release version
        id: set_release_version
        run: |
          LAST_VERSION=$(git tag --sort=committerdate | tail -1)
          echo Last tag is $LAST_VERSION
          bash ./scripts/update_version.sh $LAST_VERSION

      - name: Publish
        run: dart pub publish --force

      - name: Increment version in CHANGELOG
        run: bash scripts/increment_changelog_version.sh

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b update-changelog-${{ github.ref }}
          git add CHANGELOG.md
          git commit -m "Update incremented CHANGELOG after release ${{ github.event.release.tag_name }}"
          git push origin HEAD

      - name: Create a pull request with changelog
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Automated CHANGELOG update"
          body: "This pull request was created automatically to update the CHANGELOG after a release."
          branch: update-changelog-${{ github.ref }}
          base: main
