name: Release on Pub Dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: release-pub-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_pub_dev:
    name: Release on pub dev
    runs-on: ubuntu-latest

    timeout-minutes: 180

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.USED_LFS }}
          fetch-depth: 0

      - name: Base setup dart
        uses: dart-lang/setup-dart@v1
        with:
          environment: pub.dev

      - name: Install dependencies
        run: dart pub get

      - name: Build generated files
        shell: bash
        run: bash scripts/build_generated_files.sh

      - name: Set release version
        id: set_release_version
        run: |
          LAST_VERSION=$(git tag --sort=committerdate | tail -1)
          echo Last tag is $LAST_VERSION
          bash ./scripts/update_version.sh $LAST_VERSION

      - name: Publish
        run: dart pub publish --force
