name: Test Yaml's Lint

on:
  pull_request:
    paths:
      - "**.yaml"

concurrency:
  group: test-yaml-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: bash scripts/test_yaml_lint.sh
